# Generated by Django 5.2 on 2025-04-20 11:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('winename', models.CharField(max_length=200)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('alcohol', models.FloatField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('wineryName', models.CharField(blank=True, max_length=200, null=True)),
                ('wineryLocation', models.CharField(blank=True, max_length=200, null=True)),
                ('wineryWebsite', models.URLField(blank=True, null=True)),
                ('originCountry', models.CharField(blank=True, max_length=100, null=True)),
                ('originRegion', models.CharField(blank=True, max_length=100, null=True)),
                ('merchantName', models.CharField(blank=True, max_length=200, null=True)),
                ('merchantWebsite', models.URLField(blank=True, null=True)),
                ('tastingnotes', models.TextField(blank=True, null=True)),
                ('bottlesbought', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tasting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tastingdate', models.DateTimeField()),
                ('degurating', models.IntegerField(blank=True, null=True)),
                ('degunotes', models.TextField(blank=True, null=True)),
                ('foodpairing', models.TextField(blank=True, null=True)),
                ('bottlesDrunken', models.IntegerField(default=0)),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tastings', to='meinweinkeller.wine')),
            ],
        ),
    ]
